import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import SideBare from "@/components/SideBar/SideBare";
import Layout from "./(layout)/layout";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en">
      <body className="overflow-x-hidden">
          <div className=" flex">
             <SideBare/>
            <div className="container ">
               
                  <NavBar/>
                    {children}
              </div>
            </div>
      </body>
    </html>
  );
}
